### ISSUE TITLE
Bug: can't unmarshal int value to the cfg.Expression

### ISSUE THREAD

**Issue by vadimalekseev** [ozontech/file.d#267]
File.d with config like this:
```yaml

output:
  type: file
  workers_count: 5
```
fails with an error:

```
fatal	fd	can't create pipeline "http_file": can't unmarshal config for output: json: cannot unmarshal number into Go struct field Config.workers_count of type cfg.Expression
```
