### ISSUE TITLE
Bug: We must reset previous action after Propagate

### ISSUE THREAD

**Issue by vadimalekseev** [ozontech/file.d#278]
**Describe the bug**
Now we are not reset action busy status after ActionHold.

**To Reproduce**

```yaml
pipelines:
  ingresslogs:
    actions:
      - continue: /(^\w+)/
        field: message
        start: /^\d{1,10}#\d{1,10}\:.*/
        type: join
      - type: discard
    input:
      dir_pattern: '*'
      filename_pattern: error.log
      offsets_file: configs/ingresslog-offsets.yaml
      type: file
      watching_dir: configs/logs
    output:
      type: devnull
    settings:
      capacity: 30
      decoder: nginx_error
```

```sh
$ while true; do echo "2023/01/25 08:27:27 [error] request: \"$(date +%s) POST /\", upstream: \"g\", host: \"ams\"" >> configs/logs/error.log; sleep 0.0001; done
```

It will panic after 30 seconds.

**Additional context**
Version: all
Platform: all
