### ISSUE TITLE
Feature: Flexible antispammer settings

### ISSUE THREAD

**Issue by vadimalekseev** [ozontech/file.d#323]
Let's support flexible antispammer settings. Currently, all events pass through it. We must begin to separate important logs from the rest and give API to manage this behavior.

The new config will look like this:
```yaml
pipelines:
  k8s:
    settings:
      antispammer:
        threshold: 1000 # moves from settings.antispam_threshold
        pass_policy: 'field_equal' # it may be one of: 'field_equal', 'white_list', 'black_list'

       # policy-specific fields

       # field_equal settings:
       field: 'important'
       value: true

      # white_list/black_list settings:
       field: 'service'
       list: ['payment-api', 's3-server', 'logd']
```

**Comment by vadimalekseev** [comment]
After discussion with colleagues, they came up with a temporary solution before introducing their own language:
```yaml
pipelines:
  k8s:
    settings:
      antispam_threshold: 1000
      antispam_except:
        - cond: 'and'
          value:
            - func: 'prefix'
              value: ['{"error":"debug"']
              case_insensitive: true
              invert: true
            - func: 'contains'
              value: ['{"service":"alerts-agent"']
              case_insensitive: false
        - cond: 'and'
          value:
            - func: 'prefix'
              value: ['{"error":"debug"']
              case_insensitive: true
              invert: true
```
