### ISSUE TITLE
Feature: Allow using single null or string in values field in do_if

### ISSUE THREAD

**Issue by HeadHunter483** [ozontech/file.d#554]
Currently do_if accepts values only as a list of strings or nulls. Sometimes there is only one value to check field op against, so it would be more comfortable to write single value in config instead of list.

Example in current format requiring list:

```yaml
do_if:
  op: equal
  field: service
  values: [test-service]
```

Want format for single values:

```yaml
do_if:
  op: equal
  field: service
  values: test-service
```
