### ISSUE TITLE
Bug: SASL SCRAM-SHA-256 in kafka output plugin

### ISSUE THREAD

**Issue by kirillov6** [ozontech/file.d#572]
**Describe the bug**
Kafka output plugin doesn't work with SASL mechanism `SCRAM-SHA-256`.

**To Reproduce**
1. Run kafka in docker - `docker-compose up -d` (see `docker-compose.yml` below).
2. Run file.d with - `go run ./cmd/file.d/file.d.go --config="./myconfig.yaml"` (see `myconfig.yaml` below).
3. See logs: `{"level":"fatal","ts":"2024-01-19T09:37:03.686679Z","logger":"fd.dummy.output.kafka","message":"can't create producer: kafka: client has run out of available brokers to talk to: EOF"}`

If you replace `sasl_mechanism` with `PLAIN` or `SCRAM-SHA-512` in `myconfig.yaml`, it will work.

**Expected behavior**
Kafka output plugin works with SASL mechanism `SCRAM-SHA-256`.

**Configs**
`docker-compose.yml`:
```yaml
version: "2"

services:
  zookeeper:
      image: docker.io/bitnami/zookeeper:3.9
      ports:
        - "2181:2181"
      volumes:
        - "zookeeper_data:/bitnami"
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.6
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # Zookeeper
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # Listeners
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:9092,PLAINTEXT://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://localhost:9092,PLAINTEXT://:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      # Inter broker
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      # Security
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
      - KAFKA_CLIENT_USERS=user,admin
      - KAFKA_CLIENT_PASSWORDS=pass,admin
volumes:
  kafka_data:
    driver: local
  zookeeper_data:
    driver: local
````

`myconfig.yaml`:
```yaml
pipelines:
  dummy:
    input:
      type: fake
    output:
      type: kafka
      brokers:
        - localhost:9092
      default_topic: my-topic
      is_sasl_enabled: true
      sasl_mechanism: SCRAM-SHA-256
      sasl_username: user
      sasl_password: pass
```
