### ISSUE TITLE
Bug: raw decoder corrupts input json array

### ISSUE THREAD

**Issue by DmitryRomanov** [ozontech/file.d#595]
**Describe the bug**
Input JSON array corrupts with raw-decoder

**To Reproduce**
config:

```yaml
pipelines:
  array:
    settings:
      decoder: raw
    input:
      type: http
      address: ":9400"
    actions: []
    output:
      type: stdout
```

```shell
curl "127.0.0.1:9400/input" -v -H 'Content-Type: application/json' -d '[{},{}]'
```

I've get invalid JSON in output:

```json
{"message":"[{},{}"}
```

**Expected behavior**
```json
{"message":"[{},{}]"}
```

**Additional context**
Version: 0.23.1
Platform: linux
