### ISSUE TITLE
Add postgres output plugin

### ISSUE THREAD

**Issue by ansakharov** [ozontech/file.d#62]
Required output plugin for pgsql.
Plugin must collect batch of events and write it into DB.
Config should contain DB fields with column name, type and uniqueness.
For first implementation required: integer, string, timestamp pgtypes.
Fields that have unique constraint should have `unique: true`.
DB request timeout and retry count and retention should be configurable.

Config suggesstion:
```yaml
    output:
      type: postgres
      batch_flush_timeout: "5s"
      db_request_timeout: "3000ms"
      retention: "50ms"
      batch_size: 2 * 1
      strict: false 
      host: 0.0.0.0
      port: 54320
      dbname: postgres
      user: postgres
      password: my_password   
      table: s3index
      columns:
        - name: service
          type: string
          unique: false
        - name: host
          type: string
          unique: true
        - name: first_date 
          type: timestamp
          unique: false
        - name: last_date
          type: timestamp
          unique: false
        - name: s3_url
          type: string
          unique: false
        - name: domain
          type: string
          unique: false
```
