### ISSUE TITLE
Feature: Change throttle limit distribution logic

### ISSUE THREAD

**Issue by kirillov6** [ozontech/file.d#669]
Now with config:
```yml
default_limit: 3000
limit_distribution:
  field: level
  ratios:
    - ratio: 0.1
      values:
        - debug
```
10% of limit will be reserved for debug logs.
That is, if the service does not write debug logs at all, only 2700 logs will be written, then they will start throttling.
The logic needs to be changed so that with the same config there is no reservation and no more than 10% of debug logs can be written. Then, for example, if the service does not write debug logs at all, all 3000 logs are written.
