### ISSUE TITLE
Bug: elasticsearch - "not_set" instead of time in index

### ISSUE THREAD

**Issue by KisKisSandra** [ozontech/file.d#792]
**Describe the bug**
The index name has "not_set" instead of time, even if "index_values" ​​is present

**To Reproduce**
1. Config:
```
pipelines:
  my_service:
    input:
      type: journalctl
      offsets_file: /tmp/tmp.yaml
      journal_args: [CONTAINER_NAME=my-service, -f, -a]
    actions:
    - type: keep_fields
      fields: [SYSLOG_TIMESTAMP, CONTAINER_TAG, IMAGE_NAME, MESSAGE]
    output:
      type: elasticsearch
      endpoints: [http://127.0.0.1:9200]
      index_format: my-service-%
      index_values: [time]
```
2.  "my-service-not_set" index in elasticsearch

**Expected behavior**
"my-service-2025-02-28" index in elasticsearch

**Additional context**
Version: 0.52.0
Platform: Ubuntu 22.04
